apiVersion: v1
kind: Service
metadata:
  name: user-management-and-authentication
  labels:
    app: user-management-and-authentication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-management-and-authentication