---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-and-authentication
  labels:
    app: user-management-and-authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management-and-authentication
  template:
    metadata:
      labels:
        app: user-management-and-authentication
    spec:
      containers:
        - name: user-management-and-authentication
          image: username/user-management-and-authentication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-management
  labels:
    app: profile-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-management
  template:
    metadata:
      labels:
        app: profile-management
    spec:
      containers:
        - name: profile-management
          image: username/profile-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-and-news-feed-management
  labels:
    app: post-and-news-feed-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-and-news-feed-management
  template:
    metadata:
      labels:
        app: post-and-news-feed-management
    spec:
      containers:
        - name: post-and-news-feed-management
          image: username/post-and-news-feed-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: user-management-and-authentication
  labels:
    app: user-management-and-authentication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-management-and-authentication


---


apiVersion: v1
kind: Service
metadata:
  name: profile-management
  labels:
    app: profile-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: profile-management


---


apiVersion: v1
kind: Service
metadata:
  name: post-and-news-feed-management
  labels:
    app: post-and-news-feed-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: post-and-news-feed-management

