apiVersion: v1
kind: Service
metadata:
  name: post-and-news-feed-management
  labels:
    app: post-and-news-feed-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: post-and-news-feed-management